version: "3.8"

services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      # Variables de entorno para desarrollo local
      - DATABASE_URL=${DATABASE_URL}
      - SECRET_KEY=${SECRET_KEY}
      - ENVIRONMENT=${ENVIRONMENT}
      - DEBUG=${DEBUG}
      - LOG_LEVEL=${LOG_LEVEL}
    volumes:
      - ./src:/app/src
    restart: unless-stopped
