name: laive-api
description: API de Laive con FastAPI

services:
  - name: api
    type: app
    source:
      type: image
      image: laive-api:latest
    ports:
      - "8000:8000"
    environment:
      # Variables de entorno usando referencias de EasyPanel
      - DATABASE_URL=${DATABASE_URL}
      - SECRET_KEY=${SECRET_KEY}
      - ENVIRONMENT=${ENVIRONMENT}
      - DEBUG=${DEBUG}
      - LOG_LEVEL=${LOG_LEVEL}
    healthcheck:
      path: /
      port: 8000
      interval: 30s
      timeout: 10s
      retries: 3
